<style media="screen">
    ul,li{
        padding:0;
        margin:0;
        list-style: none;
    }
    ul{
        width:100%;
        background: blue;
    }
    ul li{
        line-height: 30px;
        text-align: center;
    }
</style>
<template id="">
    <ul>
        <li>
            <h2>{{name}}</h2>
            hello
        </li>
        <li>1helloasdf</li>
        <li>2hello</li>
        <li>3hello</li>
        <li>4hellsdafo</li>
        <li>5hello</li>
        <li>6hello</li>
        <li>7hello</li>
        <li>8helloasdfsdafsd</li>
        <li>9hello</li>
        <li>10hellsdafasdfsdao</li>
        <li>11hello</li>
        <li>12hello</li>
        <li>13helloasdf</li>
        <li>14hello</li>
        <li>15hello</li>
        <li>16hellsdafo</li>
        <li>17hello</li>
        <li>18hello</li>
        <li>19hello</li>
        <li>20helloasdfsdafsd</li>
        <li>21hello</li>
        <li>22hellsdafasdfsdao</li>
        <li>23hello</li>
        <li>24hello</li>
        <li>25helloasdf</li>
        <li>26hello</li>
        <li>27hello</li>
        <li>28hellsdafo</li>
        <li>29hello</li>
        <li>30hello</li>
        <li>31hello</li>
        <li>32helloasdfsdafsd</li>
        <li>33hello</li>
        <li>34hellsdafasdfsdao</li>
        <li>35hello</li>
        <li>36hello</li>
        <li>37helloasdf</li>
        <li>38hello</li>
        <li>39hello</li>
        <li>40hellsdafo</li>
        <li>41hello</li>
        <li>42hello</li>
        <li>43hello</li>
        <li>44helloasdfsdafsd</li>
        <li>45hello</li>
        <li>46hellsdafasdfsdao</li>
        <li>47hello</li>
        <li>48hello</li>
        <li>49helloasdf</li>
        <li>50hello</li>
        <li>hello</li>
        <li>hellsdafo</li>
        <li>hello</li>
        <li>hello</li>
        <li>hello</li>
        <li>helloasdfsdafsd</li>
        <li>hello</li>
        <li>hellsdafasdfsdao</li>
        <li>hello</li>
        <li>hello</li>
        <li>helloasdf</li>
        <li>hello</li>
        <li>hello</li>
        <li>hellsdafo</li>
        <li>hello</li>
        <li>hello</li>
        <li>hello</li>
        <li>helloasdfsdafsd</li>
        <li>hello</li>
        <li>hellsdafasdfsdao</li>
        <li>hello</li>
        <li>hello</li>
        <li>helloasdf</li>
        <li>hello</li>
        <li>hello</li>
        <li>hellsdafo</li>
        <li>hello</li>
        <li>hello</li>
        <li>hello</li>
        <li>helloasdfsdafsd</li>
        <li>hello</li>
        <li>hellsdafasdfsdao</li>
        <li>hello</li>
    </ul>
</template>
<script type="text/javascript">
    module.exports = {
        data(){
            return{
                name:'spaOne'
            }
        },
        created(){

        }
    }
</script>
